apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: loadgenheadless-prod
  name: loadgenheadless-prod
  namespace: loadgen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadgenheadless-prod
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: loadgenheadless-prod
    spec:
      containers:
      - env:
        - name: ET_APM_SERVER_DEFAULT
          value: APM
        - name: ET_ANGULAR_FRONTEND_URL
          value: http://easytravel-angular.easytravel-production.domain.placeholder:80             
        image: dynatrace/easytravel-headless-loadgen:3356
        name: angular-loadgen-prod
